version: "3"

services:
  nuxt:
    restart: always
    build: ./frontend
    expose:
      - "3000"
    links:
      - django

  nginx:
    volumes:
      - ./nginx/site:/usr/share/nginx/html:rw
      - ./nginx/conf.d.local:/etc/nginx/conf.d:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./django/media:/usr/share/nginx/html/media:rw
