# Generated by Django 2.1 on 2021-02-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_projectsearch_partner_names'),
        ('search', '0025_projectsearch_partner_names 2'),
    ]

    operations = [
    ]
